### ISSUE TITLE
hoek module error is ouccured

### ISSUE THREAD

**Issue by jeonghwan-kim** [agendor/sample-hapi-rest-api#1]
Thank you for share the sample hapi code scaffold.
I'm considering use of it in my project.
When I run your sample code, it works find.
However when I try to adding [good](https://github.com/hapijs/good) module for logging system, the error is occurred.
Beleow is error message and my code that is added.

Error msg

```
sample-hapi-rest-api/node_modules/hoek/lib/index.js:407
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Plugin missing name
    at Object.exports.assert (/Users/Chris/Documents/sandbox/sample-hapi-rest-api/node_modules/hoek/lib/index.js:407:11)
    at internals.Pack._register (/Users/Chris/Documents/sandbox/sample-hapi-rest-api/node_modules/hapi/lib/pack.js:191:11)
    at internals.Pack.register (/Users/Chris/Documents/sandbox/sample-hapi-rest-api/node_modules/hapi/lib/pack.js:178:10)
    at module.exports (/Users/Chris/Documents/sandbox/sample-hapi-rest-api/src/logger.js:16:15)
    at Object.<anonymous> (/Users/Chris/Documents/sandbox/sample-hapi-rest-api/index.js:37:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Code added

``` javascript
var opts = {
  opsInterval: 1000,
  reporters: [{
    reporter: require('good-console'),
    args:[{ request: '*', log: '*', error: '*', ops: '*'}]
  }, {
    reporter: require('good-file'),
    args: ['src/log/access-log', { request: '*', log: '*'}]
  }, {
    reporter: require('good-file'),
    args: ['src/log/error-log', { error: '*' }]
  }]
};

server.pack.register({
  plugin: require('good'),
  options: opts
}, function (err) {
  if (err) {
    throw err;
  }
});
```

Could you help me?

**Comment by tuliomonteazul** [comment]
It's seems to be a problem with Hapi version. The sample is using the version 3.0.
Look at the [docs](https://github.com/hapijs/hapi/blob/49afc5ac780f66c73ae51786aa826f3fae2675c3/docs/Reference.md#packregisterplugin-options-callback) for `server.pack.register` definition in that version.

I did a test here updating to Hapi version 7.5. It works but there are some breaking changes to solve on `index.js` and `src/validate/task.js`

Another option would be to still use the 3.0 old version and change syntax to somenthing like:

```
// not tested code
server.pack.register({
  name: 'good-plugin',
  version: '1.0',
  plugin: require('good'),
  options: opts
}, function (err) {
  if (err) {
    throw err;
  }
});
```

**Comment by jeonghwan-kim** [comment]
Thanks for answer. :+1:
